name: BungeeTabListPlus
main: codecrafter47.bungeetablistplus.BukkitPlugin
version: ${project.version}
api-version: 1.13
authors:
  - CodeCrafter47
softdepend: [Factions, Vault, VanishNoPacket, SuperVanish, PremiumVanish, PlayerPoints, PlaceholderAPI]
