useAsyncThreads: true
# setting this to true increases the performance of the plugin. If the plugin 
# generates a lot of errors in the server logs you might consider setting this 
# to false




# This is for internal use only. DO NOT CHANGE.
configVersion: 1